"""empty message

Revision ID: 5a2500ff4a87
Revises: 
Create Date: 2018-03-23 16:14:43.601610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a2500ff4a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('facility_name', sa.String(length=50), nullable=True),
    sa.Column('facility_picture', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gateway',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('useable', sa.Boolean(), nullable=True),
    sa.Column('home_id', sa.String(length=24), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('province', sa.String(length=25), nullable=True),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('p_id', sa.String(length=24), nullable=True),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('order', sa.SmallInteger(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['p_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('contract_tel', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('salt', sa.String(length=50), nullable=True),
    sa.Column('createTime', sa.DateTime(), nullable=True),
    sa.Column('lastTime', sa.DateTime(), nullable=True),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('facility_knowledge',
    sa.Column('knowledge_id', sa.String(length=24), nullable=True),
    sa.Column('facility_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ),
    sa.UniqueConstraint('knowledge_id', 'facility_id', name='uix_facility_knowledge')
    )
    op.create_table('ins',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('ins_picture', sa.LargeBinary(), nullable=True),
    sa.Column('location_id', sa.String(length=50), nullable=True),
    sa.Column('ins_address', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('admin_user_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_menu',
    sa.Column('role_id', sa.String(length=24), nullable=True),
    sa.Column('menu_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.UniqueConstraint('menu_id', 'role_id', name='uix_role_menu')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('role_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.UniqueConstraint('user_id', 'role_id', name='uix_role_user')
    )
    op.create_table('community',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('community_picture', sa.LargeBinary(), nullable=True),
    sa.Column('detail_address', sa.String(length=255), nullable=True),
    sa.Column('save_distance', sa.Integer(), nullable=True),
    sa.Column('eva_distance', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('ins_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['ins_id'], ['ins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility_ins',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('facility_id', sa.String(length=24), nullable=True),
    sa.Column('ins_id', sa.String(length=24), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.ForeignKeyConstraint(['ins_id'], ['ins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ins',
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('ins_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['ins_id'], ['ins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.UniqueConstraint('user_id', 'ins_id', name='uix_ins_user')
    )
    op.create_table('home',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('community_id', sa.String(length=24), nullable=True),
    sa.Column('admin_user_id', sa.String(length=24), nullable=True),
    sa.Column('detail_address', sa.String(length=255), nullable=True),
    sa.Column('link_name', sa.String(length=50), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('latitude', sa.Float(asdecimal=True), nullable=True),
    sa.Column('alternate_phone', sa.String(length=50), nullable=True),
    sa.Column('gateway_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateway.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homeuser',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('home_id', sa.String(length=24), nullable=True),
    sa.Column('apply_time', sa.DateTime(), nullable=True),
    sa.Column('if_confirm', sa.Boolean(), nullable=True),
    sa.Column('confirm_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('gateway_id', sa.String(length=24), nullable=True),
    sa.Column('sensor_place', sa.String(length=255), nullable=True),
    sa.Column('sensor_type', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('home_id', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateway.id'], ),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_alarm_record',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=50), nullable=True),
    sa.Column('if_confirm', sa.Boolean(), nullable=True),
    sa.Column('home_id', sa.String(length=24), nullable=True),
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['home_id'], ['home.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_alarm',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('sensor_id', sa.String(length=24), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('alarm_object', sa.String(length=50), nullable=True),
    sa.Column('alarm_value', sa.Float(), nullable=True),
    sa.Column('alarm_time', sa.DateTime(), nullable=True),
    sa.Column('confirm_time', sa.DateTime(), nullable=True),
    sa.Column('is_timeout', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.String(length=24), nullable=True),
    sa.Column('is_confirm', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensorhistory',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('sensor_id', sa.String(length=24), nullable=True),
    sa.Column('sensor_state', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensorhistory')
    op.drop_table('sensor_alarm')
    op.drop_table('user_alarm_record')
    op.drop_table('sensor')
    op.drop_table('homeuser')
    op.drop_table('home')
    op.drop_table('user_ins')
    op.drop_table('facility_ins')
    op.drop_table('community')
    op.drop_table('user_role')
    op.drop_table('role_menu')
    op.drop_table('ins')
    op.drop_table('facility_knowledge')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('menu')
    op.drop_table('location')
    op.drop_table('knowledge')
    op.drop_table('gateway')
    op.drop_table('facility')
    # ### end Alembic commands ###
