"""initial migration

Revision ID: 788906e0f9c7
Revises: 5a2500ff4a87
Create Date: 2018-03-23 18:01:55.473470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '788906e0f9c7'
down_revision = '5a2500ff4a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('home_name', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'home_name')
    # ### end Alembic commands ###
